[Settings]
# Timeout for code execution in seconds
timeout = 2

# Memory limit for the program in MB
memoryLimit = 512

# Path to the directory where student programs are stored
programPath = .

# Programming language (C++, Java, Python)
language = C++

# Evaluative testcases
evaluatives = ET1,ET2,ET3,ET4 

